# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Growl
version:      0.99
version_from: lib/Net/Growl.pm
installdirs:  site
requires:
    Carp:                          0
    Exporter:                      0
    IO::Socket:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
